### ISSUE TITLE
Websocket

### ISSUE THREAD

**Issue by robmarkcole** [SimonBiggs/scriptedforms#79]
Getting:
```
Installing collected packages: websocket
Successfully installed websocket-0.2.1
Robins-MacBook-Air:scriptedforms robincole$ scriptedforms quick-start.md --token boo
Traceback (most recent call last):
  File "/anaconda3/bin/scriptedforms", line 11, in <module>
    load_entry_point('scriptedforms==0.5.7', 'console_scripts', 'scriptedforms')()
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/anaconda3/lib/python3.6/site-packages/scriptedforms-0.5.7-py3.6.egg/scriptedforms/__init__.py", line 27, in <module>
    from .scriptedforms import load, main
  File "/anaconda3/lib/python3.6/site-packages/scriptedforms-0.5.7-py3.6.egg/scriptedforms/scriptedforms.py", line 33, in <module>
    from websocket import create_connection
ImportError: cannot import name 'create_connection'
```

**Comment by robmarkcole** [comment]
Tried:
```
Robins-MacBook-Air:scriptedforms robincole$ pip install websocket-client
Collecting websocket-client
  Downloading websocket_client-0.47.0-py2.py3-none-any.whl (200kB)
    100% |████████████████████████████████| 204kB 3.3MB/s
Requirement already satisfied: six in /anaconda3/lib/python3.6/site-packages (from websocket-client)
Installing collected packages: websocket-client
Successfully installed websocket-client-0.47.0
```

Getting:
```
Robins-MacBook-Air:scriptedforms robincole$ scriptedforms quick-start.md --token boo
Traceback (most recent call last):
  File "/anaconda3/bin/scriptedforms", line 11, in <module>
    load_entry_point('scriptedforms==0.5.7', 'console_scripts', 'scriptedforms')()
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/anaconda3/lib/python3.6/site-packages/scriptedforms-0.5.7-py3.6.egg/scriptedforms/__init__.py", line 27, in <module>
    from .scriptedforms import load, main
  File "/anaconda3/lib/python3.6/site-packages/scriptedforms-0.5.7-py3.6.egg/scriptedforms/scriptedforms.py", line 43, in <module>
    from notebook.notebookapp import NotebookApp
  File "/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 38, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "/anaconda3/lib/python3.6/site-packages/jinja2/__init__.py", line 81, in <module>
    _patch_async()
  File "/anaconda3/lib/python3.6/site-packages/jinja2/__init__.py", line 77, in _patch_async
    from jinja2.asyncsupport import patch_all
  File "/anaconda3/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 13, in <module>
    import asyncio
  File "/anaconda3/lib/python3.6/asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/anaconda3/lib/python3.6/asyncio/base_events.py", line 17, in <module>
    import concurrent.futures
  File "/anaconda3/lib/python3.6/site-packages/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/anaconda3/lib/python3.6/site-packages/concurrent/futures/_base.py", line 381
    raise exception_type, self._exception, self._traceback
                        ^
SyntaxError: invalid syntax
```

**Comment by SimonBiggs** [comment]
Hehe, let me make a requirements.txt so you can make an exact copy of my environment. I'll leave the requirements.txt around as it seems to help with issues like these. Give me an hour or so until after I get the kids to bed :)

**Comment by SimonBiggs** [comment]
I think the key is I didn't install any packages, I uses the standard lib websocket...

**Comment by SimonBiggs** [comment]
Fixed in https://github.com/SimonBiggs/scriptedforms/commit/cd02ad9a413db8ba2fdaa948ba6bac49f2591323

Can you re-download, then re-run `pip install -e .` and let me know if it is fixed.

**Comment by robmarkcole** [comment]
Now getting:
```
Robins-MacBook-Air:scriptedforms robincole$ scriptedforms quick-start.md --token boo
Traceback (most recent call last):
  File "/anaconda3/bin/scriptedforms", line 11, in <module>
    load_entry_point('scriptedforms==0.5.7', 'console_scripts', 'scriptedforms')()
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/anaconda3/lib/python3.6/site-packages/scriptedforms-0.5.7-py3.6.egg/scriptedforms/__init__.py", line 27, in <module>
    from .scriptedforms import load, main
  File "/anaconda3/lib/python3.6/site-packages/scriptedforms-0.5.7-py3.6.egg/scriptedforms/scriptedforms.py", line 43, in <module>
    from notebook.notebookapp import NotebookApp
  File "/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 38, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "/anaconda3/lib/python3.6/site-packages/jinja2/__init__.py", line 81, in <module>
    _patch_async()
  File "/anaconda3/lib/python3.6/site-packages/jinja2/__init__.py", line 77, in _patch_async
    from jinja2.asyncsupport import patch_all
  File "/anaconda3/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 13, in <module>
    import asyncio
  File "/anaconda3/lib/python3.6/asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/anaconda3/lib/python3.6/asyncio/base_events.py", line 17, in <module>
    import concurrent.futures
  File "/anaconda3/lib/python3.6/site-packages/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/anaconda3/lib/python3.6/site-packages/concurrent/futures/_base.py", line 381
    raise exception_type, self._exception, self._traceback
                        ^
SyntaxError: invalid syntax
```

**Comment by SimonBiggs** [comment]
Most recent commit adds the requirements.txt file:
https://github.com/SimonBiggs/scriptedforms/commit/d1538f1aec2d61f3c53ef0e3f9d556293a57758d

Can you let me know if installing with that makes a difference? If it does would you be able to work out what dependency is causing the issue so that I can force it within setup.py

**Comment by robmarkcole** [comment]
Same error I believe - perhaps jijna is the cause?
```
Robins-MacBook-Air:scriptedforms robincole$ scriptedforms quick-start.md --token boo
Traceback (most recent call last):
  File "/anaconda3/bin/scriptedforms", line 11, in <module>
    load_entry_point('scriptedforms==0.5.7', 'console_scripts', 'scriptedforms')()
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/anaconda3/lib/python3.6/site-packages/scriptedforms-0.5.7-py3.6.egg/scriptedforms/__init__.py", line 27, in <module>
    from .scriptedforms import load, main
  File "/anaconda3/lib/python3.6/site-packages/scriptedforms-0.5.7-py3.6.egg/scriptedforms/scriptedforms.py", line 43, in <module>
    from notebook.notebookapp import NotebookApp
  File "/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 38, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "/anaconda3/lib/python3.6/site-packages/jinja2/__init__.py", line 81, in <module>
    _patch_async()
  File "/anaconda3/lib/python3.6/site-packages/jinja2/__init__.py", line 77, in _patch_async
    from jinja2.asyncsupport import patch_all
  File "/anaconda3/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 13, in <module>
    import asyncio
  File "/anaconda3/lib/python3.6/asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/anaconda3/lib/python3.6/asyncio/base_events.py", line 17, in <module>
    import concurrent.futures
  File "/anaconda3/lib/python3.6/site-packages/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/anaconda3/lib/python3.6/site-packages/concurrent/futures/_base.py", line 381
    raise exception_type, self._exception, self._traceback
                        ^
SyntaxError: invalid syntax
```

**Comment by SimonBiggs** [comment]
The weird thing is I'm not personally using Jinja...

**Comment by SimonBiggs** [comment]
Could you try a Python 3.5 conda environment. See if that does the trick?

**Comment by SimonBiggs** [comment]
Given the error type around async stuff I just did a stab in the dark change, there was something I had in there that didn't need to be in there. Could you try the most recent commit:
https://github.com/SimonBiggs/scriptedforms/commit/9a7de3b27ae1c65d689c48302f094a76f5e9e935

Let me know if you have any luck.

Also, try run `pip install -e . --upgrade`

 and see if that fixes it...

**Comment by robmarkcole** [comment]
OK doing this properly and creating a venv now

**Comment by SimonBiggs** [comment]
For that, you just need to follow the development install instruction:

https://github.com/SimonBiggs/scriptedforms#installing-scriptedforms-from-the-github-source

**Comment by robmarkcole** [comment]
OK up an running, will try the API
